CREATE TABLE USERS (
    USER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(64),
    LAST_NAME VARCHAR(64),
    EMAIL VARCHAR(128) UNIQUE,
    PHONE_NUMBER VARCHAR(32),
    ADDRESS VARCHAR(256),
    CITY VARCHAR(64),
    STATE VARCHAR(2),
    ZIPCODE VARCHAR(12),
    PASSWORD VARCHAR(256) NOT NULL,
    ROLE VARCHAR(20) NOT NULL CHECK (role IN ('ROLE_ADMIN', 'ROLE_CUSTOMER', 'ROLE_SELLER'))
);

